### ISSUE TITLE
3pts As a patient, I want to create a patient account on this platform

### ISSUE THREAD

**Issue by Aayushi1130** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#3]
**User story**
As a patient, I want to create a patient account on this platform so that I can make reservations with therapists. 

**Acceptance criteria**
Patients are able to create an account with their personal email addresses and passwords. 

**Definition of Done**
Patients are able to create accounts on this website, each account must link to an email address. If the email address has registered, give a warning and stop proceeding with the request.

**Comment by MengZhou11** [comment]
**User story**
As a patient, I want to be able to create an account so that I can log in.

**Acceptance criteria**
Patients are able to create an account with a unique username, password and email address. 

**Definition of Done**
Patients are able to create accounts on this website, each account must link to an email address. If the email address has registered, give warning and stop proceeding the request.
